services:
  - type: web
    name: livekit-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: LIVEKIT_API_KEY
        value: devkey
      - key: LIVEKIT_API_SECRET
        value: secret
    ports:
      - port: 7880
        protocol: tcp
