services:
  - type: web
    name: livekit-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: LIVEKIT_API_KEY
        value: devkey
      - key: LIVEKIT_API_SECRET
        value: secret
      - key: LIVEKIT_SERVER_URL
        value: wss://<your-service-name>.onrender.com
